version: "3.9"
services:
    web:
        container_name: nombre_proyecto_web
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "81:80"
        volumes:
            - ./../:/var/www/html
