version: "3.9"
services:
    web:        
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "81:80"
        volumes:
            - ./:/var/www
            - ./public:/var/www/html
    mysql:        
        image: mysql:5.7.35
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3307:3306"
